/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio2;

import java.util.TreeSet;

/**
 *
 * @author Abel
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());
    
    public static TreeSet<ProductoEj2> listaProductos = new TreeSet<>();

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("TP6 De Todo S.A.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAdministracion = new javax.swing.JMenu();
        jMenuItemProductos = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuNombre = new javax.swing.JMenuItem();
        jMenuItemPrecio = new javax.swing.JMenuItem();
        jMenuItemRubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jMenuAdministracion.setText("Administracion");

        jMenuItemProductos.setText("Productos");
        jMenuItemProductos.addActionListener(this::jMenuItemProductosActionPerformed);
        jMenuAdministracion.add(jMenuItemProductos);

        jMenuBar1.add(jMenuAdministracion);

        jMenuConsultas.setText("Consultas");

        jMenuNombre.setText("Por Nombre");
        jMenuNombre.addActionListener(this::jMenuNombreActionPerformed);
        jMenuConsultas.add(jMenuNombre);

        jMenuItemPrecio.setText("Por Precio");
        jMenuItemPrecio.addActionListener(this::jMenuItemPrecioActionPerformed);
        jMenuConsultas.add(jMenuItemPrecio);

        jMenuItemRubro.setText("Por Rubro");
        jMenuItemRubro.addActionListener(this::jMenuItemRubroActionPerformed);
        jMenuConsultas.add(jMenuItemRubro);

        jMenuBar1.add(jMenuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNombreActionPerformed
       /* escritorio.removeAll();
        escritorio.repaint();
        vistaPorNombre vpn = new vistaPorNombre();
        vpn.setVisible(true);
        escritorio.add(vpn);*/
        
        // Descomentar esto al crear la consulta por Nombre:
        vistaPorNombre vpn = new vistaPorNombre();
        vpn.setVisible(true);
        escritorio.add(vpn);
        escritorio.moveToFront(vpn);
    }//GEN-LAST:event_jMenuNombreActionPerformed

    private void jMenuItemPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrecioActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        
        // Descomentar esto al crear la consulta por Precio:
        // ConsultaPrecioView cpv = new ConsultaPrecioView();
        // cpv.setVisible(true);
        // escritorio.add(cpv);
        // escritorio.moveToFront(cpv);
    }//GEN-LAST:event_jMenuItemPrecioActionPerformed

    private void jMenuItemProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductosActionPerformed
        //Esto cierra si es que habia otro panel abierto
        escritorio.removeAll();
        escritorio.repaint();
        
        GestionProductosView vista = new GestionProductosView();
        vista.setVisible(true);
        escritorio.add(vista);
        escritorio.moveToFront(vista);
        
        
    }//GEN-LAST:event_jMenuItemProductosActionPerformed

    private void jMenuItemRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRubroActionPerformed
//        escritorio.removeAll();
//        escritorio.repaint();
        
        // Descomentar esto al crear la consulta por Rubro:
            FrmListadoRubro flr = new FrmListadoRubro();
            flr.setVisible(true);
            escritorio.add(flr);
            escritorio.moveToFront(flr);
   
    }//GEN-LAST:event_jMenuItemRubroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenuAdministracion;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuItemPrecio;
    private javax.swing.JMenuItem jMenuItemProductos;
    private javax.swing.JMenuItem jMenuItemRubro;
    private javax.swing.JMenuItem jMenuNombre;
    // End of variables declaration//GEN-END:variables
}
